#!/usr/bin/env bash
# Create a PKCS12 release keystore and write/update keystore.properties.
#
#   ./scripts/generate-keystore.sh
#   ./scripts/generate-keystore.sh --force
#   ./scripts/generate-keystore.sh --store-password 'your-password'
#
# Then build the signed APK with:
#   ./scripts/build-signed-apk.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

KEYSTORE_DIR="$ROOT/keystore"
KEYSTORE_FILE="${KEYSTORE_FILE:-$KEYSTORE_DIR/release.keystore}"
PROPERTIES_FILE="$ROOT/keystore.properties"
ALIAS="${KEY_ALIAS:-vobizvoip}"
DNAME="${KEY_DNAME:-CN=Enetro VoIP, OU=Mobile, O=Enetro, C=IN}"
VALIDITY_DAYS=10000
STORE_PASSWORD="${KEYSTORE_PASSWORD:-}"
KEY_PASSWORD="${KEY_PASSWORD:-}"
FORCE=0
PROMPT=0

usage() {
  cat <<'EOF'
Usage: ./scripts/generate-keystore.sh [options]

  --force              Replace an existing keystore (breaks updates of existing installs)
  --prompt             Ask for the store password instead of generating one
  --alias NAME         Key alias (default: vobizvoip)
  --dname NAME         Certificate distinguished name
  --out PATH           Keystore path (default: keystore/release.keystore)
  --store-password PW  Store password (otherwise generated, or --prompt)
  --key-password PW    Key password (default: same as store password)
  -h, --help           Show this help

Environment (same meaning as the flags):
  KEYSTORE_FILE, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD, KEY_DNAME

Always writes both:
  keystore/release.keystore   PKCS12 keystore (mode 600, gitignored)
  keystore.properties         storeFile, storePassword, keyAlias, keyPassword

Then run ./scripts/build-signed-apk.sh. Back up both files; they are gitignored.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1 ;;
    --prompt) PROMPT=1 ;;
    --alias)
      ALIAS="${2:?--alias requires a value}"
      shift
      ;;
    --dname)
      DNAME="${2:?--dname requires a value}"
      shift
      ;;
    --out)
      KEYSTORE_FILE="${2:?--out requires a path}"
      shift
      ;;
    --store-password)
      STORE_PASSWORD="${2:?--store-password requires a value}"
      shift
      ;;
    --key-password)
      KEY_PASSWORD="${2:?--key-password requires a value}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if ! command -v keytool >/dev/null 2>&1; then
  echo "keytool not found. Install JDK 17 and ensure it is on PATH." >&2
  exit 1
fi

if [[ "$KEYSTORE_FILE" != /* ]]; then
  KEYSTORE_FILE="$ROOT/$KEYSTORE_FILE"
fi

if [[ -f "$KEYSTORE_FILE" && "$FORCE" -ne 1 ]]; then
  echo "Keystore already exists: $KEYSTORE_FILE" >&2
  echo "Re-run with --force to replace it (this breaks updates of existing installs)." >&2
  exit 1
fi

if [[ "$PROMPT" -eq 1 ]]; then
  if [[ ! -t 0 ]]; then
    echo "--prompt requires an interactive terminal." >&2
    exit 1
  fi
  read -r -s -p "Store password: " STORE_PASSWORD
  echo
  read -r -s -p "Confirm store password: " confirm
  echo
  if [[ -z "$STORE_PASSWORD" || "$STORE_PASSWORD" != "$confirm" ]]; then
    echo "Passwords were empty or did not match." >&2
    exit 1
  fi
fi

if [[ -z "$STORE_PASSWORD" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    STORE_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  else
    STORE_PASSWORD="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)"
  fi
  echo "Generated a store password and saved it in keystore.properties."
fi

KEY_PASSWORD="${KEY_PASSWORD:-$STORE_PASSWORD}"

mkdir -p "$(dirname "$KEYSTORE_FILE")"
if [[ -f "$KEYSTORE_FILE" ]]; then
  echo "Replacing existing keystore at $KEYSTORE_FILE"
  rm -f "$KEYSTORE_FILE"
fi

echo "Generating PKCS12 keystore at $KEYSTORE_FILE (alias=$ALIAS, ${VALIDITY_DAYS} days)"
keytool -genkeypair \
  -storetype PKCS12 \
  -keystore "$KEYSTORE_FILE" \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity "$VALIDITY_DAYS" \
  -storepass "$STORE_PASSWORD" \
  -keypass "$KEY_PASSWORD" \
  -dname "$DNAME"

chmod 600 "$KEYSTORE_FILE"

RELATIVE="$KEYSTORE_FILE"
if [[ "$KEYSTORE_FILE" == "$ROOT/"* ]]; then
  RELATIVE="${KEYSTORE_FILE#"$ROOT"/}"
fi

umask 077
cat > "$PROPERTIES_FILE" <<EOF
# Generated by scripts/generate-keystore.sh. Do not commit this file.
storeFile=$RELATIVE
storePassword=$STORE_PASSWORD
keyAlias=$ALIAS
keyPassword=$KEY_PASSWORD
EOF
chmod 600 "$PROPERTIES_FILE"

echo
echo "Created keystore:"
echo "  $KEYSTORE_FILE"
echo "Updated signing properties:"
echo "  $PROPERTIES_FILE"
echo "    storeFile=$RELATIVE"
echo "    keyAlias=$ALIAS"
echo
keytool -list -keystore "$KEYSTORE_FILE" -storepass "$STORE_PASSWORD"
echo
echo "Back up both files now. They are gitignored."
echo "Build a signed APK with: ./scripts/build-signed-apk.sh"
